### ISSUE TITLE
More robust problem checking by ensuring consistent number of elements

### ISSUE THREAD

**Issue by davidlmobley** [bannanc/ManipulateXVG#2]
Currently, the code only checks to ensure every element can be converted to a float. With the current construction of .xvg files, I think you could have slightly more robust checking by also checking that the number of elements is consistent from line to line. For example: 

```
    for l in dataLines:
        goodLine = True
        for s in l.split(' '):
            try:
                float(s)
            except:
                goodLine = False
                break 
        if goodLine:
            newlines.append(l)
```

could be rewritten to attempt to parse the same number of elements on every line.

You also may be able to do this much more quickly using numpy, i.e. I think numpy has some functionality for reading numeric data from a file quickly (fromfile, perhaps?). Anytime you can avoid using `for` loops (especially nested `for` loops, as here) in favor of array operations you can potentially save a huge amount of time.

I'd be a lot more enthusiastic about releasing this as a utility function in alchemical-analysis if we could make it faster. Probably not an issue for your xvg files but if you imagine processing thousands of files with tens of thousands of lines each it could be an issue. (Nathan has data like this, IIRC).

**Comment by bannanc** [comment]
I think I have this fixed, using numpy.genfromtxt now
