### ISSUE TITLE
Exceptions for "eatting" too much data

### ISSUE THREAD

**Issue by bannanc** [bannanc/ManipulateXVG#3]
Add exceptions if "too much" of the data has disappeared... maybe some percentage, still thinking about the ideal way to do this.

**Comment by davidlmobley** [comment]
Caitlin, let me know when you think you have this stuff ready and I'll take another look.

**Comment by bannanc** [comment]
Do we have an idea of how much data is too much? 20% ? Should this be
customizable?

---

Caitlin C. Bannan
Graduate Student
Mobley Group
Chemistry Department at UC Irvine
bannanc@uci.edu

**Comment by davidlmobley** [comment]
You can set a reasonable default value and have an optional argument to
override it - that would work well. 20% sounds like a good number, or even
10%.

Thanks.

On Mon, Dec 21, 2015 at 3:17 PM, Caitlin Bannan notifications@github.com
wrote:

> Do we have an idea of how much data is too much? 20% ? Should this be
> customizable?
> 
> ---
> 
> Caitlin C. Bannan
> Graduate Student
> Mobley Group
> Chemistry Department at UC Irvine
> bannanc@uci.edu
> 
> On Mon, Dec 21, 2015 at 3:00 PM, David L. Mobley <notifications@github.com
> 
> > wrote:
> > 
> > Caitlin, let me know when you think you have this stuff ready and I'll
> > take another look.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/bannanc/ManipulateXVG/issues/3#issuecomment-166448846>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bannanc/ManipulateXVG/issues/3#issuecomment-166455226
> .

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Comment by bannanc** [comment]
OK, I'll set the default to 10%. I'm getting some weird numbers in one of
my test cases so I'll let you know when I think it's working more
completely. I should have it done tonight or tomorrow morning.

Caitlin

---

Caitlin C. Bannan
Graduate Student
Mobley Group
Chemistry Department at UC Irvine
bannanc@uci.edu

**Comment by bannanc** [comment]
I'm closing this issue, There is now an exception that is thrown if 10% or more of the data is removed.
